### ISSUE TITLE
How to handle multi page responses

### ISSUE THREAD

**Issue by github-fuf** [ImmobilienScout24/restapi-php-sdk#12]

**Comment by thebub** [comment]
Hi, 

I'm trying to use the "regionSearch" command, which does return multi-page results.
Apparently this issue was related to some kind of multi-page handling.

How was this issue solved? If it wasn't solved, how could it be solved?

Daniel

**Comment by Immocaster** [comment]
-- Please reply above this line --


Hallo,

vielen Dank für Ihre E-Mail!
Wir werden aufgrund einer bevorstehenden Geburt im Zeitraum vom
4.3.-13.3.2016 voraussichtlich sehr eingeschränkt oder gar nicht
erreichbar sein.
Danach werden wir die aufgelaufenen Anfragen gerne beantworten.

Viele Grüße,
Ihr Team von WP-ImmoMakler
