### ISSUE TITLE
OAuth.php

### ISSUE THREAD

**Issue by kaischi70** [ImmobilienScout24/restapi-php-sdk#27]
Hi, hatte heute auf einem Test-System einen OAuth-Fehler:
Fatal error: Cannot redeclare class OAuthException in .../Oauth/OAuth.php on line 8

Hat lange gedauert, den Fehler zu finden.
Es lag daran, dass in PHP die oauth-extension geladen wurde, daher gab es schon die Instanz.
Die OAuth.php sollte so angepasst werden: 

Statt:
class OAuthException extends Exception {
    // pass
}

bitte:
if (!class_exists('OAuthException')) {
  class OAuthException extends Exception {
    // pass 
  }
}

oder:
if (!extension_loaded('OAuth')) {
  class OAuthException extends Exception {
    // [...]
  }
}

**Comment by mriehl** [comment]
Hi,

ist zwar nicht meine Baustelle hier aber ein "pull-request" würde die Bearbeitung sicherlich beschleunigen.
