### ISSUE TITLE
Die Methode $oImmocaster->getApplicationTokenAndSecret($sUser) kann nicht aufgerufen werden

### ISSUE THREAD

**Issue by amenk** [ImmobilienScout24/restapi-php-sdk#29]
Es kommt ein Fehler, dass es die Methode nicht gibt. Sie ist private.
Die Dokumentation (Einführung) funktioniert daher so nicht.

**Comment by fmielke** [comment]
Ist in der Doku falsch. Bitte print_r($oImmocaster->getAllApplicationUsers(array('string'=>true))); verwenden, es wird eine Liste mit Usern in der Datenbank ausgegeben.
