### ISSUE TITLE
Checken ob die Funktion "mime_content_type" existiert vor Benutzung!

### ISSUE THREAD

**Issue by roegi** [ImmobilienScout24/restapi-php-sdk#31]
Die Datei Immobilienscout.php verwendet die Funktion mime_content_type(), welche nicht in allen PHP  Umgebungen verfügbar ist.
Ein einfacher check vorher in derselben Bedingung, löst das Problem bereits, da so dann die Alternativmethode verwendet wird:

... if(function_exists('mime_content_type') && $aFileInfoMime = mime_content_type($aArgs['file'])) ...

**Comment by fmielke** [comment]
Danke!

matthiasnattke hat einen Pull Request erzeugt, welcher gemerged wurde: 2e4c78cebd1da21e8d1a4cd356e0856d6e6f8ee5
