### ISSUE TITLE
Function mysql_list_tables() is deprecated....

### ISSUE THREAD

**Issue by antonfunk** [ImmobilienScout24/restapi-php-sdk#33]
mysql funktionen sind seit 5.5 veraltet....

**Comment by fmielke** [comment]
Danke für den Hinweis. Werden wir demnächst patchen.

**Comment by tholu** [comment]
Prepared Statements wären auch zur Vermeidung von SQL-Injection sehr praktisch (habe den Code nicht intensiv auf bestehende Lücken geprüft). Akzeptiert ihr generell Pull Requests?

**Comment by fmielke** [comment]
Ja klar ;)

**Comment by tholu** [comment]
@fmielke Alles klar, ich warte gerade noch auf eine Antwort für meine API-Key-Anfrage, und sehe mir das anschließend mal genauer an.

**Comment by tholu** [comment]
@fmielke Leider immer noch keine Antwort, oder wie lange dauert das in der Regel? Schade.

**Comment by fmielke** [comment]
Hallo @tholu, kommen aktuell leider nicht dazu. Sorry. Falls der Schuh drückt - wir akzeptieren Pull Requests.

**Comment by tholu** [comment]
@fmielke Ohne API-Key kann ich das SDK schlecht verwenden, also auch keine Verbesserungen durch Pull Requests erstellen.

**Comment by fmielke** [comment]
@tholu, wir haben alle API Anträge abgearbeitet. Wann ist der eingegangen, und mit welchem Betreff?

**Comment by tholu** [comment]
@fmielke 07.12.2015 mit dem Betreff "Freischaltung API Contentpartner" an service@immobilienscout24.de - danke!

**Comment by fmielke** [comment]
merge request done. https://github.com/ImmobilienScout24/restapi-php-sdk/commit/81e3a2b2650454bc96e103944c514143a905a656
