### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by webbird** [ImmobilienScout24/restapi-php-sdk#35]
Ich weiß nicht, wie häufig das vorkommt, aber zumindest meine Entwicklungsumgebung läuft hinter einem Proxy. Daher habe ich die Rest.php um eine Funktion setProxy() erweitert und die beiden Stellen, an denen ein curl_init() gemacht wird, entsprechend ergänzt. Besteht Interesse an diesem Patch?

**Comment by fmielke** [comment]
Sicherlich besteht Interesse. Wäre super, wenn das Feature ein- und ausgeschaltet werden kann, siehe beispielsweise enableRequestDebug.

**Comment by webbird** [comment]
Wozu ein- und ausschalten? Proxy konfiguriert -> nutze ihn, nicht konfiguriert -> nutze ihn nicht.

**Comment by fmielke** [comment]
Oder so ;)

**Comment by webbird** [comment]
Vermutlich wollt Ihr das als Pull Request?

**Comment by fmielke** [comment]
Wäre ein Traum ;)

**Comment by DimitrIS24** [comment]
So ein süßer OpenSource Flirt...;)))



Vom Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Fabian Mielke <notifications@github.com>
Datum:25.08.2015 11:27 (GMT+01:00)
An: ImmobilienScout24/restapi-php-sdk <restapi-php-sdk@noreply.github.com>
Cc:
Betreff: Re: [restapi-php-sdk] Proxy (#35)


Wäre ein Traum ;)

**Comment by DimitrIS24** [comment]
Sorry, habe ich an die falsche Adresse geanntwortet?


Vom Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Fabian Mielke <notifications@github.com>
Datum:25.08.2015 11:27 (GMT+01:00)
An: ImmobilienScout24/restapi-php-sdk <restapi-php-sdk@noreply.github.com>
Cc:
Betreff: Re: [restapi-php-sdk] Proxy (#35)


Wäre ein Traum ;)
