### ISSUE TITLE
Wiki Einführung

### ISSUE THREAD

**Issue by webbird** [ImmobilienScout24/restapi-php-sdk#36]
Vielleicht bin ich ja zu doof, aber ich kriege es nicht hin, die Applikation zu zertifizieren. In der Einführung steht unter anderem:

// Test ob Benutzer schon zertifiziert ist
        if($oImmocaster->getApplicationTokenAndSecret($sUser))

Die Funktion getApplicationTokenAndSecret() ist aber private und kann von außerhalb der Rest.php gar nicht aufgerufen werden! Wo also soll der Code zum Zertifizieren eingebunden werden?

**Comment by fmielke** [comment]
Da hast du Recht. Es sollte als Check in der index.php print_r($oImmocaster->getAllApplicationUsers(array('string'=>true))); aufgerufen werden. Dann siehst du, ob der User bereits in der Datenbank steht.
