### ISSUE TITLE
mysql_connect() is deprecated

### ISSUE THREAD

**Issue by timeens** [ImmobilienScout24/restapi-php-sdk#39]

**Comment by jan-koch** [comment]
Just installed the API and came across this issue as well.
I went through Data/MySQL.php and replaced all "mysql_" functions with "mysqli_" functions.

So far it seems to be working.

**Comment by timeens** [comment]
mysql functions are deprecated since PHP 7.  If someone is still running into troubles you can use this -> https://github.com/dshafik/php7-mysql-shim

Notice the "Why You Shouldn't Use This Library" section. :+1:

**Comment by fmielke** [comment]
merge request done. https://github.com/ImmobilienScout24/restapi-php-sdk/commit/81e3a2b2650454bc96e103944c514143a905a656
