### ISSUE TITLE
Warning: session_start(): Cannot send session cache limiter - headers already sent

### ISSUE THREAD

**Issue by jan-koch** [ImmobilienScout24/restapi-php-sdk#41]
Hey,
I'm trying to integrate the api into a WordPress plugin. Seems that the session handling conflicts with WordPress' sessions. I get this error when loading the plugin:

`Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /Applications/XAMPP/xamppfiles/htdocs/restapi-php-sdk-master/wp-includes/formatting.php:5011) in /Applications/XAMPP/xamppfiles/htdocs/restapi-php-sdk-master/wp-content/plugins/immoscout_rest_api/Immocaster/Immobilienscout/Rest.php on line 2`

Can you help me with that? I don't have much experience in working with sessions to be honest.

Thanks,
Jan

**Comment by jan-koch** [comment]
Just

**Comment by fmielke** [comment]
Just? @jan-koch

**Comment by jan-koch** [comment]
Sorry, opening that thread didn't make sense as there's a discussion about session handling going on already in #38. Forgot to complete that "Just" statement after closing this.
